version: '3.8'
services:
  frontend:
    container_name: react-frontend
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
